### ISSUE TITLE
Licensing issues

### ISSUE THREAD

**Issue by xxxserxxx** [panotza/gosmc#2]
gosmc is MIT licensed, but it includes smc.c and smc.h which are both GPL. Any software embedding GPL code must be licensed under the GPL; it can not (legally) be relicensed under MIT.

https://www.tawesoft.co.uk/kb/article/mit-license-faq

> Can I use GPL-licensed code in my MIT-licensed project?
> 
> No. The project as a whole must conform to the terms of the GPL license and must be distributed under the terms of that license. Therefore such a project as a whole must be distributed as GPL, but can still contain MIT-licensed software.

**Comment by panotza** [comment]
I'm so sorry. I didn't know about GPL license before. by the way I have changed license to GPL v3. thanks a lot.
