### ISSUE TITLE
gosmc MIT licence incompatible with included Apple's GPL-licenced smc.h/c files

### ISSUE THREAD

**Issue by Lomanic** [panotza/gosmc#3]
Hi @panotza,

gosmc is licenced under [the MIT licence](https://github.com/panotza/gosmc/blob/313fdb5fcf7fbf7c87f048dd04731a6c5a567eac/LICENSE), but it includes GPL-licenced files [smc.h](https://github.com/panotza/gosmc/blob/313fdb5fcf7fbf7c87f048dd04731a6c5a567eac/smc.h#L5-L17) and [smc.c](https://github.com/panotza/gosmc/blob/313fdb5fcf7fbf7c87f048dd04731a6c5a567eac/smc.h#L5-L17) that don't include any [linking exception](https://en.wikipedia.org/wiki/GPL_linking_exception). Anything building against gosmc _statically links_ this code as it's imported/called with cgo, so to my knowledge (IANAL), this library (and its [downstream  users](https://pkg.go.dev/github.com/panotza/gosmc?tab=importedby)) may have to be GPL-licenced ([this is debated](https://en.wikipedia.org/w/index.php?title=GNU_General_Public_License&oldid=960975922#Linking_and_derived_works), but gopsutil was also using a derivative of these files and had to remove them because of their licence in https://github.com/shirou/gopsutil/issues/518). You may have to relicence to GPLv2 to be on the safe side.

Regards

ping @xxxserxxx

**Comment by Lomanic** [comment]
Duplicates #2.

**Comment by panotza** [comment]
I'm so sorry. I didn't know about GPL license before. by the way I have changed license to GPL v3. thanks a lot.

**Comment by dkorunic** [comment]
Acknowledging this as downstream user (dkorunic/iSMC) and relicensing as well.
